### ISSUE TITLE
Couldnt jump to my langage

### ISSUE THREAD

**Issue by kanedayo** [golang/tour#1013]
Context: https://tour.golang.org/welcome/2

error message:
Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information.

---
Thank you for your all efforts.

**Comment by ALTree** [comment]
Thanks for reporting this.

We don't control or deploy the tour translations (we just link to them, but they are maintained by native speakers of the language). The issue should be reported to the Japanese tour's owner, at https://github.com/atotto/go-tour-jp/issues.

I'm closing this issue, since unfortunately there's nothing the Go Project can do to fix it; we don't have access to that tour deployment.
