### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by arunammu** [golang/tour#103]
if every page contains the explanation part for each program then it would be so great for beginning users like me thanks

**Comment by ALTree** [comment]
Some code snippets have a more complete explanation on the left, but in general while learning a new programming language it's useful to spend some time studying code snippets without having a complete explanation of what they do. I believe it's part of the learning experience.

Moreover we must avoid making the tour being too verbose, because that would annoy the more experienced programmers that just want to use it to learn Go's syntax. It hard to strike a balance, and it's hard to design a tutorial that works for everyone.
