### ISSUE TITLE
tour: Default Selection & time channels

### ISSUE THREAD

**Issue by guedou** [golang/tour#1033]
Context: https://tour.golang.org/concurrency/6

First of all thanks for the tour! It is a really perfect introduction to Go! As a new comer, I will suggest that the page "Default Selection" indicates that `time.Tick()` and `time.After()` return Go channels. I could provide a PR if you think that could improve the tour.

**Comment by ALTree** [comment]
Thanks for reporting this; in my opinion that is clear enough just by looking at the code. After being defined, they're immediately used with `<-` which at this point the reader knows is a channel operation. I'd would avoid cluttering the text with too much information. Also it can be productive to leave something out from the text so that the reader can make an effort to read and learn something from the code snippets, too.

Closing here.
