### ISSUE TITLE
tour: slice append behavior confusing

### ISSUE THREAD

**Issue by headkace** [golang/tour#1111]
Context: https://tour.golang.org/moretypes/15
Is not clear in this example why appending 1 item to a slice causes both capacity and length to grow by 1 (makes sense), but when 3 items are appended in one operation, the length grows by 3 (as expected), but the capacity grows by 4! and this was not expected.  Here is output from unmodified code-run:
```
len=0 cap=0 []
len=1 cap=1 [0]
len=2 cap=2 [0 1]
len=5 cap=6 [0 1 2 3 4]
```

**Comment by ALTree** [comment]
The doc only says "If the backing array of s is too small to fit all the given values a bigger array will be allocated.". There's no guarantee about the new size. In fact, doing 3 -> 4 -> 5 -> 6 would be a *terrible* idea because re-allocating is an expensive operation (you need to copy the whole array to the new location). That's why slices actually double in capacity, to minimize the number of re-allocations.
