### ISSUE TITLE
tour: (suggestion) available languages on first page

### ISSUE THREAD

**Issue by WhereIsX** [golang/tour#1115]
Context: https://tour.golang.org/welcome/2

Currently, the go tour is available in several languages, which is awesome.  I think it'd be even more awesome if this accessibility feature was more accessible  and on the first page of the tour

**Comment by ALTree** [comment]
Currently is on the second page, which I think it's optimal. Of course 1st page would make it even more visible, but at the same time it's really important to have a good, descriptive but also brief landing page which simply tells you what the tour is.

Of course if you don't speak English at all it'll be a little confusing, but the tour website itself is mostly linked from English pages anyway, so that doesn't seem a huge issue.

**Comment by WhereIsX** [comment]
fair that we'd like the first page to be welcoming by being brief and descriptive. at the same time, perhaps it's possible to slip in a short sentence at the beginning such as "also available in other languages", linking to the second page?

may I also add that I think the hamburger menus description of the second page be changed from "Go local" to "Go in other languages" to be more descriptive? 

when I read `Go local` my first thought isn't other languages.  if anything, it sounds like Go on my local machine, which sounds a lot like the option below it, `Go offline (optional)`
