### ISSUE TITLE
tour: timeout running program - Go build failed - on any tour page today

### ISSUE THREAD

**Issue by EduardTsoy** [golang/tour#1126]
Context: https://tour.golang.org/basics/1 or any other

timeout running program
Go build failed.

<img src="https://user-images.githubusercontent.com/10813578/108692012-2a526680-750d-11eb-8e47-17b7b35438bb.png" width="256">

**Comment by EduardTsoy** [comment]
P.S. The problem disappeared after a while, but maybe somebody might look into - to prevent such occasions in the future.

**Comment by EduardTsoy** [comment]
After a couple hours the problem came back:

![imagen](https://user-images.githubusercontent.com/10813578/108710780-8de88e00-7525-11eb-8d9e-c74fd4535eea.png)

**Comment by EduardTsoy** [comment]
The same problem on play.golang.org:

<img src="https://user-images.githubusercontent.com/10813578/108712344-b07ba680-7527-11eb-9c87-ec2a21a03040.png" width="256">

**Comment by EduardTsoy** [comment]
Duplicate of: https://github.com/golang/go/issues/39016

**Comment by git-ruttmann** [comment]
Same problem currently active on https://play.golang.org/ with the "Hello playground" sample.

The HTTP response to the compile call returns after 6 seconds with this json:
{"Errors":"timeout running program","Events":null,"Status":0,"IsTest":false,"TestsFailed":0}

Reproducible from Germany since 15 minutes. Maybe missing server resources?

**Comment by git-ruttmann** [comment]
Update 21:14 MESZ: playground works again

**Comment by ALTree** [comment]
There was some issue with the server, should be fixed now. See golang/go#44537.
