### ISSUE TITLE
tour: Hyperlink follows non existent page

### ISSUE THREAD

**Issue by Elyasin** [golang/tour#1254]
Context: https://tour.golang.org/methods/21

The link to show the many implementations fails to show an appropriate result. It seems that the page is down or non existent.

**Comment by ALTree** [comment]
It works for me. Maybe a temporary issue? Are you still unable to reach the page?

**Comment by Elyasin** [comment]
I am still unable to reach the page. I tried with Brave and Firefox, which should be the latest available versions.

**Comment by ALTree** [comment]
I'm still able to see the page on Firefox. 

What does the website return? Are you sure it's not just slow? (I've seen people reporting it being slow, for example from Australia). Where are you located? Maybe blocked in your country?

**Comment by Elyasin** [comment]
I still see the same behaviour. I am in Germany. I browse the internet and can see any other web site I am visiting. Google, DuckDuckGo, The Tour of Go, GitHub, my emails, ... with both Brave and Firefox.
JavaScript enabled. Not sure about Ad Blocker (none installed); if browser has one then assume standard settings; I did not change those. Internet connection is fast.

Below the screen shot.

![image](https://user-images.githubusercontent.com/1544924/135976933-58e4868b-83f4-44c7-9ad8-bb4b078ac3ed.png)

**Comment by ALTree** [comment]
Thanks. 

So... that website is not associated with the Go Project, it's a google thing. Clearly it doesn't work on your computer, but it's not something we can fix on this side. Assuming you are able to load the homepage at https://cs.opensource.google/, the *Send Feedback* link in the 3-dots menu (top-right) should let you send a bug report to whoever is in charge of that website.

Not linking to it in the tour is not an option, because right now pkg.go.dev doesn't support that kind of code search (and the link works for most people). I'm closing this issue because I don't believe it's actionable here (as an issue in the Go Tour).
