### ISSUE TITLE
tour: Exercise Maps

### ISSUE THREAD

**Issue by ivanbarlog** [golang/tour#143]
Context: http://127.0.0.1:3999/moretypes/23

Hi guys, I am trying to solve excercise for maps section and I've got this solution:

```go
package main

import (
	"golang.org/x/tour/wc"
	"strings"
)

func WordCount(s string) map[string]int {
	words := strings.Fields(s)
	result := make(map[string]int)

	for _, v := range words {
		result[v] =  strings.Count(s, v)
	}

	return result
}

func main() {
	wc.Test(WordCount)
}
```

It hasn't passed the test but values in my solution seems to be right just in different order than the test expects.

```
PASS
 f("I am learning Go!") = 
  map[string]int{"I":1, "am":1, "learning":1, "Go!":1}
PASS
 f("The quick brown fox jumped over the lazy dog.") = 
  map[string]int{"lazy":1, "dog.":1, "quick":1, "fox":1, "over":1, "the":1, "The":1, "brown":1, "jumped":1}
FAIL
 f("I ate a donut. Then I ate another donut.") =
  map[string]int{"donut.":2, "Then":1, "another":1, "I":2, "ate":2, "a":4}
 want:
  map[string]int{"ate":2, "a":1, "donut.":2, "Then":1, "another":1, "I":2}
Program exited.
```

I am not sure if this is bug or an intention. If intention could someone please help me and tell me how the solution should work? I haven't found any pattern (eg. sorting results alphabetically, sorting by value etc).

**Comment by robphoenix** [comment]
Hi @ivanbarlog, there is a slight difference in your solution where you've counted the letter `a` 4 times. `strings.Count()` considers `a` as a letter rather than a word and so also counts any occurrence of it within the other words. Try replacing this line: `result[v] =  strings.Count(s, v)` with this: `result[v]++`.

Hope this helps. If it does please consider closing this issue, thanks!

**Comment by ivanbarlog** [comment]
Thanks @robphoenix that worked :+1:
