### ISSUE TITLE
tour: Explain the meaning of 'Name: syntax' in the description

### ISSUE THREAD

**Issue by JESii** [golang/tour#152]
Context: https://tour.golang.org/moretypes/5

What is the '`Name:` syntax? I looked in the documentation and could find no reference to this.

If it's the same as the "dot syntax" referred to earlier in the lesson, then please use the same terminology to avoid confusion.

**Comment by zakora** [comment]
The `Name:` syntax refers to this line of Go code on this page:
```go
	v2 = Vertex{X: 1}  // Y:0 is implicit
```

It is a way of initializing a struct by providing pair(s) of `field name: value`. In this case, `v2` is initialized by providing only the field named `X` and the value `1`, the `Vertex` struct also has a `Y` field that will take the default value for `int`: 0 since it is not specified at init time.

Hope this makes it clearer to you, that page was not very clear for me at first and had to re-read it.

**Comment by JESii** [comment]
Yes, thanks; that helps. I'd like to push a change to clarify that and will let you know when that's ready
