### ISSUE TITLE
tour: Exercise: Images misleading description

### ISSUE THREAD

**Issue by igsky** [golang/tour#180]
Context: https://tour.golang.org/methods/25

"Exercise: Images" lesson states: 

1. "Remember the picture generator you wrote earlier?" 
Nope.

2. "`At` should return a color; the value `v` in the last picture generator corresponds to `color.RGBA{v, v, 255, 255}` in this one."  
The problem is that there is no "last picture generator" anywhere to be found in preceding lessons, therefore it's impossible to reuse value `v` from there. (looks like null pointer exception to me, jk) One might consider "Images" lesson to be "last picture generator", but there is no `v` there.

**Comment by ahoischen** [comment]
There was an image generator exercise quite some time ago when arrays and slices were introduced. It returned a grayscale (bluescale) image. However, I, like most others, haven't written down the contents of each lesson alongside their URL to quickly refer to them should another lesson ask me to. And since this lesson was more than a module away I really didn't care enough to search for it.

My suggestion would be to place a link in the description to remind people of the previous lesson.

**Comment by ALTree** [comment]
Fixed by 03133cc9684f0d84f4b533c0b064683d8822e587. Closing.
