### ISSUE TITLE
tour: Too much mathematics in the tour

### ISSUE THREAD

**Issue by goalain** [golang/tour#193]
Context: https://tour.golang.org/

Overall the tour is great, but there is way too much mathematics related stuff.
I am programming over 30 years, Fortran, C, PHP and others , and never used a Fibonacci, mostly never using floats, calculating surfaces etc..
Most of my work is about strings and logic.
While trying to focus on understanding Go in the tour, I find myself spending a lot of time deciphering the maths part, bit rotation, etc.
I.E. 
https://tour.golang.org/flowcontrol/5 , is it about If ?
https://tour.golang.org/moretypes/24 , is the focus on Function values ?
https://tour.golang.org/methods/4 , is the focus on Pointer receivers ?
https://tour.golang.org/methods/7 , is the focus on Methods and pointer indirection ?
 
In contrast
https://tour.golang.org/methods/17 is a great (funny and relaxing) example

Maybe Go is only a language for mathematicians?

**Comment by Pixdigit** [comment]
I think I know what you want to say. But for example the Fibonacci program does not require any context and is simple and has a strictly determined output. However when you have string processing the is a lot  of ambiguity. Just the task "Capitalize every word":

- Is a word defined by that it is surrounded by " " ?
- What about other whitespace?
- What if it begins with a symbol ?
- What about encoding?
- How to deal with empty strings?
- What if the input language is Arabic and you have no idea about how to write Arabic?
- What about characters that are already upper case?
- etc.

So such task need much more explanation. Mathematical functions on the other hand have no ambiguity. fib(0) is always 1. And there are no exceptions to the Fibonacci sequence. Or the Rot13 task. The Wikipedia article clearly defines behaviour.

**Comment by ALTree** [comment]
> Maybe Go is only a language for mathematicians?

Not really. 

The problem is that it's *very* hard to come up with simple examples and exercises short enough to not be too annoying if you don't draw from mathematics (trust me, I've tried). Almost every exercise and every package in the standard library will be 10x longer and harder to explain if you adventure in other domains (like encodings, files, strings, etc...). Math functions are often simple (put something in, something comes out), so are very easy to code from scratch (or call in examples). That's why they're used in the tour.

**Comment by deniztoprak** [comment]
I think the problem is not about the domain but the **complexity** of the given example. A developer who doesn't have a solid background in mathematics shouldn't have to struggle to understand the code example. A much simpler function could be used to ease the learning process e.g. a function that simply adds two values. The goal of the exercise is to learn function values in go in the most simple and generic way possible. [Stackoverflow guidelines](https://stackoverflow.com/help/mcve) stipulate that a code example must be **minimal**, **complete** and **verifiable**. A minimal code is _as little as possible that still produces the same problem_.
