### ISSUE TITLE
tour: Rand does not seem to work correctly

### ISSUE THREAD

**Issue by hdost** [golang/tour#207]
Context: http://127.0.0.1:3999/basics/1

After running it repeatedly returns 1 every single time.

**Comment by NathanZook** [comment]
Some sort of initialization is needed.

**Comment by robphoenix** [comment]
From: https://tour.golang.org/basics/1

> Note: the environment in which these programs are executed is deterministic, so each time you run the example program rand.Intn will return the same number. (To see a different number, seed the number generator; see rand.Seed.)

**Comment by NathanZook** [comment]
What I mean by "needed" is "needs to be added to the code".  It's not surprising that calls to functions in `rand` are deterministic without a prior call to `rand.Seed`.  It's surprising that `rand.Seed` is not being called.

**Comment by robphoenix** [comment]
@NathanZook  I think it's not being called because the page is discussing packages and going into seeding random numbers is off topic to that. The note on the page is clear that the same number will be repeated every time and points people to read further about `rand.Seed` if they wish.

I think the original issue has been answered here @hdost 
If there is further discussion to be had about the use of random numbers as an example then we can open a new issue @NathanZook 
Otherwise I believe this can be closed @adg
