### ISSUE TITLE
append to slice: Capacity increased by 4 after adding 3 elements

### ISSUE THREAD

**Issue by dmitriia** [golang/tour#218]
Context: http://127.0.0.1:3999/moretypes/15

len=2 cap=2 [0 1]
len=5 cap=6 [0 1 2 3 4]

**Comment by robphoenix** [comment]
The `append` function creates a new array with a larger capacity in order to hold the new slice. The capacity of this new array will often be larger than the new slice requires. In the example you've given it has a capacity of 6 but only has 5 elements. 

This behaviour is due to efficiency; it avoids an excessive number of allocations and ensures that appending a single element takes constant time on average. *(Reference: [The Go Programming Language](https://www.amazon.co.uk/Programming-Language-Addison-Wesley-Professional-Computing/dp/0134190440/ref=sr_1_1?s=books&ie=UTF8&qid=1496759398&sr=1-1&keywords=go+programming) page 89)*
It means new arrays don't necessarily need to be created every time the slice is appended to. It's like taking a couple of extra bags with you shopping in case you buy more than is on your shopping list, which saves you having to buy more bags in the shop, kind of. :smile:

Hope this helps! Please consider closing this issue if it does, thanks!

**Comment by dmitriia** [comment]
Hi Rob, thank you, I will close this.
