### ISSUE TITLE
tour: How do i print an address of the pointer to "Struct fields" ?

### ISSUE THREAD

**Issue by sepo27** [golang/tour#226]
Context: https://tour.golang.org/moretypes/4

E.g. address of the pointer to int can be printed using pointer var with no asterisk.
But printing ponter to "Struct fields" results in "Struct fields" again.

(I'm assuming the reason is to be able to access "Struct fields"s members through pointer directly,
but this introduces an inconsistency i guess)

```go
// address of pointer to int can be printed
	i := 10
	pi := &i
	fmt.Println(pi)

	// instead of address of pointer to "Struct fields", it prints "Struct fileds" again
	v := Vertex{1, 2}
	p := &v
	fmt.Println(p)
```

**Comment by pavel** [comment]
Try this:

```go
v := Vertex{1, 2}
p := &v
fmt.Printf("%p\n", p)
```

`%p` can be found in [fmt docs](https://golang.org/pkg/fmt/#hdr-Printing)

**Comment by ALTree** [comment]
It appears this was answered. Closing.

**Comment by shellbot97** [comment]
**Why This Difference?**

- Primitive Types (like int, float, etc.): When Go prints a pointer to a primitive type, it assumes that the memory address is sufficient because the value itself is simple (e.g., an integer). So, fmt.Println prints the memory address.
- Structs (and other complex types): For complex types like structs, just printing a memory address wouldn’t be as useful because you'd want to know what data the struct contains. Go's fmt.Println automatically dereferences the pointer (prints the values inside the struct) for easier debugging and understanding. It prints both the pointer (&) and the struct contents.
