### ISSUE TITLE
tour: `fallthrough` should be in `case "darwin"`

### ISSUE THREAD

**Issue by cgrushko** [golang/tour#272]
Context: https://tour.golang.org/flowcontrol/9

Change the title above to describe your issue and add your feedback here, including code if necessary

I think it'll be more useful to change the code to
```
case "darwin"
    fallthrough
case "linux"
    ....
```

I quick-read the example and thought that there's default fallthrough like in C.

**Comment by ALTree** [comment]
Not a good idea: it'll make the code snippet wrong. If you add a `fallthrough` in the "darwin" case, the program will print both "darwin" and "linux" when run on darwin, which is wrong.

That example was chosen because that kind of switch is exactly the kind that benefits of the automatic `break`. 

> I quick-read the example and thought that there's default fallthrough like in C.

Yeah but... the accompanying text is literally 2 sentences long, and one of them says "A case body breaks automatically". This will be clear to anyone that reads the text.

**Comment by cgrushko** [comment]
Ok, for your consideration. Perhaps if more people report the same we'll get a stronger signal.

That being said, perhaps there's a sample that shows both features?

> Yeah but... the accompanying text is literally 2 sentences long

They didn't invent the acronym "RTFM" because people were reading everything on the page :)

**Comment by ALTree** [comment]
I believe the example is really clear to anyone that reads the text on the left and while it's true that we could change the code that would make the example more cumbersome. Closing here
