### ISSUE TITLE
tour: why go routine doesn't receive from the channel?

### ISSUE THREAD

**Issue by zhonglzli** [golang/tour#362]
Context: https://tour.golang.org/concurrency/3

Change the title above to describe your issue and add your feedback here, including code if necessary

package main

import "fmt"

func channel(ch chan int) {
	ch <- 3
	fmt.Println(<-ch)
}

func main() {
	ch := make(chan int, 2)
	ch <- 1
	ch <- 2
	go channel(ch)
	fmt.Println(<-ch)
	fmt.Println(<-ch)
}

Here, I don't understand why 3 isn't printed out.

**Comment by WheeskyJack** [comment]
Hi,
the 3 is not printed since the main() function exits even before the channel() function has finished execution.
Hence 3 is not being printed.
If you move the println() statement from channel() to main() then you will get the 3 printed. 
This is because  <-ch is blocking call and it will wait till go routine gets executed.
BR.

**Comment by zhonglzli** [comment]
Thank you, understood. 
So if I sleep a while at the end of main, it is likely 3 will get its chance to be printed.
