### ISSUE TITLE
tour: defer stack count down example prints 'done' before it's done counting

### ISSUE THREAD

**Issue by Moshisho** [golang/tour#404]
Context: https://tour.golang.org/flowcontrol/13

What did I do? ran the code provided:
    
    package main

    import "fmt"

    func main() {
        fmt.Println("counting")

        for i := 0; i < 10; i++ {
            defer fmt.Println(i)
        }

        fmt.Println("done")
    }

Expected to see:
_counting
9
8
7
6
5
4
3
2
1
0
done_

What I actually saw:
_counting
done
9
8
..._

Using `defer` at the start of the defer stack solves it :)

    package main

    import "fmt"

    func main() {
        fmt.Println("counting")

        defer fmt.Println("done")

        for i := 0; i < 10; i++ {
            defer fmt.Println(i)
        }

    }

**Comment by bgadrian** [comment]
That is the point, to see what defer does. At a first glance you were expected to see `9,8..0. Done`, but because `defer` calls are executed AFTER the function is executed (so after the Done), the result is `Done 9...0`.
More info on the[ official blog post](https://blog.golang.org/defer-panic-and-recover)

**Comment by ALTree** [comment]
WAI, as explained above. Closing.
