### ISSUE TITLE
tour: possible typo in making-slices

### ISSUE THREAD

**Issue by sigilioso** [golang/tour#433]
Context: https://tour.golang.org/moretypes/13

Maybe I'm wrong as I'm a newbie... but here:

```
b := make([]int, 0, 5) // len(b)=0, cap(b)=5

b = b[:cap(b)] // len(b)=5, cap(b)=5
b = b[1:]      // len(b)=4, cap(b)=4
```

The last `cap(b)=4` shouldn't be `cap(b)=5`?

**Comment by bgadrian** [comment]
The comment is correct, you can even run the code to see for yourself.
If you move the start position (str pointer), to the right of the original array, the capacity will shrink, because the internal array will remain the same length, and you can use only the "slice" between start index and the end. 
If you do 
`b = b[:3]` the capacity will remain 5, you can expand the slice to use 4,5 if you need.

https://blog.golang.org/go-slices-usage-and-internals

Also the internal array is not circular.

**Comment by sigilioso** [comment]
I understand. Thanks!
