### ISSUE TITLE
tour: [Answer to exercise: Slices]

### ISSUE THREAD

**Issue by li-jie-li** [golang/tour#46]
Context: https://tour.golang.org/moretypes/18

The question is vague, nowhere to verify the answer.
Thanks,

**Comment by alebaffa** [comment]
what do you mean by "_verify the answer_"? The exercise asks you to implement whatever you like that creates a slice, there's no right or wrong answer. Please, specify what you mean so that we can help you or make the exercise more clear for everybody, otherwise I think this issue could be closed. Thank you!

**Comment by ALTree** [comment]
I think they wanted a solution to the exercise. The solutions are here:

https://github.com/golang/tour/tree/master/solutions
