### ISSUE TITLE
tour: In the method pointers section, one of the example functions is called Abs(), which actually returns the hypotenuse of a vertex

### ISSUE THREAD

**Issue by dscottboggs** [golang/tour#536]
Context: https://tour.golang.org/methods/4

In this page, the Abs() function should be called Hypot() or Hypotenuse(). Note that the previous lesson (methods/3) has a function called Abs() that actually does return an absolute value.

**Comment by ALTree** [comment]
This is on purpose because later (https://tour.golang.org/methods/9), the `Abser` interface is introduced:

```
type Abser interface {
	Abs() float64
}
```

and it is shown that both `(f MyFloat) Abs()` and `(v *Vertex) Abs()` implement it, with different meanings (for a float64 it's the absolute value, for a vertex is the absolute length measured as the distance from the origin.

It doesn't seem possible to rename the Vertex method without a complete overhaul of the whole chapter.

**Comment by dscottboggs** [comment]
oh, you're right, my mistake.

**Comment by ALTree** [comment]
> Would it be possible then to include a note at this first instance of Abs() in this context to make it a bit easier for readers to understand? There is precedent for this in Newton’s Method for square roots elsewhere in the tour.

The `methods/4` slide is already quite verbose and the `Abser` interface is introduce just 4 slides after, I don't think it would be worth it.

> Additionally, there is still an error in the example code where we first see Abs() used for both float64 and Vertex. (Though, that is a different issue.)

Not sure what you mean here, could you elaborate? Or open an issue about this, if you prefer.
