### ISSUE TITLE
tour: slice, append

### ISSUE THREAD

**Issue by gjohann7** [golang/tour#547]
Context: https://tour.golang.org/moretypes/15

Qual lógica foi usada para a extensão do slice de array?
Usando o código disponibilizado no tópico "Appending to a slice" (append.go)
no meu PC, obtive o valor de capacidade (capacity) diferente do que foi mostrado
na execução do código online.

Esse foi o resultado obtido no meu PC:

![untitled](https://user-images.githubusercontent.com/41028368/42481706-341611e0-83ba-11e8-95bb-ba0679acffd7.png)

Esse foi o resultado obtido no código online:

![untitled1](https://user-images.githubusercontent.com/41028368/42481814-b55bd0dc-83ba-11e8-8d78-d5a4b8501114.png)

Agradeço desde já.

**Comment by ALTree** [comment]
> Qual lógica foi usada para a extensão do slice de array?

This is an internal implementation detail, but if you are curious, you can take a look at the `growslice` runtime function, here:

https://github.com/golang/go/blob/c78b7693abc1de4fa76d28ebf4c6ef9dcf0a68bb/src/runtime/slice.go#L98

> Usando o código disponibilizado no tópico "Appending to a slice" (append.go)
no meu PC, obtive o valor de capacidade (capacity) diferente do que foi mostrado
na execução do código online.

This is expected. The playground environment (where the tour example run) is 32bit, while your machine is likely a 64bit architecture. Since the backing-array growing policy is an internal implementation detail, it's expected that you may see different results on different architectures.

Closing here, since it's not a bug.

**Comment by freediver9000** [comment]
This should be mentioned in the tutorial
