### ISSUE TITLE
What is the tour release process?

### ISSUE THREAD

**Issue by bgadrian** [golang/tour#571]
I have looked around but have't found how and when the tour new versions are released. 

I've noticed that the [live version](https://tour.golang.org) still doesn't have commits accepted 30 days ago, so we have to trigger a process? or who should we poke to make it happen?

**Comment by ALTree** [comment]
AFAIK there is no schedule. Basically you poke @andybons if you think changes accumulated since the last deployment are worth a re-deployment, and if that's the case he'll re-deploy the tour. 

Considering we recently merged a fix for that annoying white box UI issue (#544), I think it might be worth to re-deploy.

**Comment by andybons** [comment]
I deployed from HEAD to tour.golang.org. If anything seems missing please let me know here.

@ALTree is correct. In the future, just file a bug and it should get triaged to someone on the team who has permission to deploy.

I’d like to get to “deploy on green” so that we don’t have to manually deploy for low-risk properties and these issues won’t come up in the future. Until we have a good plan for that, feel free to just poke us. :)
