### ISSUE TITLE
tour: 'cannot' instead of 'can not' in error string makes process take too long

### ISSUE THREAD

**Issue by Rolfdv** [golang/tour#595]
Context: https://tour.golang.org/methods/20
While working on the above exercise, I received the "process took too long" message if my return string if this was the function
```
func (e ErrNegativeSqrt) Error() string {
	return fmt.Sprintf("cannot Sqrt negative number: %v", float64(e))
}
```

Changing the string to this:
`"can not Sqrt negative number: %v"`

Caused running to succeed, with all correct answers.
How come the spelling of 'cannot'/'can not' causes this issue?

Full code given here (process takes too long):

```
package main

import (
	"math"
	"fmt"
)

type ErrNegativeSqrt float64

func (e ErrNegativeSqrt) Error() string {
	return fmt.Sprintf("cannot Sqrt negative number: %v", float64(e))
}

func Sqrt(x float64) (float64, error) {
	if x < float64(0) {
		return 0, ErrNegativeSqrt(x)
	}
	
	z := 1.0

	for {
		z = (z*z - x) / (2 * z)
		if math.Abs(z*z-x) < 0.00000001 {
			if z < 0 {
				z = 0 - z
			}
			fmt.Println("z*z:", z*z)
			fmt.Println("x:", x)
			fmt.Println("z found:", z)
			return z, nil
		}
	}

	return z, nil
}

func main() {
	fmt.Println(Sqrt(2))
	fmt.Println(Sqrt(-2))
}
```

**Comment by ALTree** [comment]
I suspect the "process took too long" was a temporary error but it got cached (since the playground caches programs using the hash of the code to avoid re-running them). The underlying issue here is that temporary errors (like temporary timeouts or out-of-memory errors) should not be cached. This is
https://github.com/golang/go/issues/26926 which was fixed recently (but I think the update playground has yet to be deployed).

I *think* this will be fixed on the patched playground, so I'm closing this issue.
