### ISSUE TITLE
tour: [https://tour.golang.org/concurrency/10]

### ISSUE THREAD

**Issue by wangxi19** [golang/tour#614]
Context: https://tour.golang.org/concurrency/10

右边那个输入代码运行的地方, 如果把代码输入框拖到最下面, 就拖不上去了。 会挡住 run 按钮。

if the right code editor has been dragged on the bottom, then it cann't be rollbak and the run button has been covered

**Comment by ALTree** [comment]
Even if the buttons disappeared at the bottom of the editor, you can drag the lower border up with the mouse and fix the layout. You have to over the cursor at the bottom of the screen until it turns into an hand and then you can drag. See:

![issue-614](https://user-images.githubusercontent.com/3586803/46247370-9eef4c80-c40a-11e8-9d68-2cd65eeb6931.gif)

Closing here, since I don't think there's a bug.
