### ISSUE TITLE
tour: Sqrt function must have parenthesis for improving readabiility

### ISSUE THREAD

**Issue by sourabh1031** [golang/tour#622]
Context: https://tour.golang.org/methods/9

Missing Parenthesis in line 14 in Sqrt as it is a function.

**Comment by bgadrian** [comment]
Can you try in a different browser, like incognito mode? I think it is a local problem, and only on your browser.

If this is the case please close the issue thanks!

**Comment by sourabh1031** [comment]
Actually, it is not working both in normal as well as the incognito mode in the chrome as private browsing in Firefox. I have tried even on a mobile browser but still the same.

**Comment by bgadrian** [comment]
Ok let me explain

1. `math.Sqrt2` is a constant see the source 
https://golang.org/pkg/math/#pkg-constants

2. That code was not modified since 2016 https://github.com/golang/tour/blob/master/content/methods/interfaces.go it should work if you hit Run

What error do you receive? I do not think the error is related to the code anyway.

**Comment by sourabh1031** [comment]
actually I thought Sqrt to be a function but actually, it is a constant here.no problem closing this now and thanks for clarifying my doubt.

**Comment by bgadrian** [comment]
Sure, `Sqrt` is a public function, `Sqrt2` is a public constant.
