### ISSUE TITLE
tour: wrong link to the zh (simplified) tour

### ISSUE THREAD

**Issue by supersensen** [golang/tour#662]
hi guys, i found some error on the simple-chinese version tour.
"https://tour.go-zh.org/"  should be "https://go-tour-zh.appspot.com/"
and
on "https://go-tour-zh.appspot.com/"
if u click the "RUN" button it will saying "Error communicating with remote server."

THANK U:)

Context: https://tour.golang.org/welcome/2

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by ALTree** [comment]
Thanks for the report.

We don't control or deploy the tour translations, so the "communicating with remote server." error should be reported to the owner of the zh tour.

Regarding the link: I'm not sure it would be a good idea to change it now, since the tour at the second link is broken too, at the moment. But we can change the link when it gets fixed.

**Comment by OlingCat** [comment]
Hi, the Chinese translation of go tour is https://tour.go-zh.org/, the GAE version is deprecated.

**Comment by ALTree** [comment]
Simplified chinese translation is now online. Closing here.
