### ISSUE TITLE
tour: append.go appears to be wrong file

### ISSUE THREAD

**Issue by robstarling** [golang/tour#738]
Context: https://tour.golang.org/moretypes/15

The page (and left-text) are about the builtin "append" function, but the code-example on the right, despite being called "append.go", appears to be about channels and goroutines and does not once use "append".

**Comment by ALTree** [comment]
Hi, and thanks for the report.

I don't see what you're describing when I click on that link. This is what I see:

![Screenshot_2019-03-24_14-06-31](https://user-images.githubusercontent.com/3586803/54879840-34a9e880-4e3e-11e9-9312-fb8ed61f124b.png)

Please try to clean your browser's cache and/or clicking the "reset" button under the code example on the right on that page, and see if this fixes the issue.

I'm closing this issue, since I don't believe this is a server issue or an issue with the tour, but feel free to comment here if you think I'm mistaken.

**Comment by robstarling** [comment]
Reset fixed it. No idea how it got confused. Thanks!
