### ISSUE TITLE
tour: wrong comment on v3 outcome

### ISSUE THREAD

**Issue by sgandon** [golang/tour#748]
Context: https://tour.golang.org/moretypes/5
the comment is wrong here
`v3 = Vertex{Y:4}      // X:0 and Y:0`
should be 
`v3 = Vertex{Y:4}      // X:0 and Y:4`

**Comment by ALTree** [comment]
Hi,

there's no such line in the code example on that page. The code read:

```
v3 = Vertex{}      // X:0 and Y:0
```

Which is correct.

My guess is that someone using the same browser changed the code to experiment with the example. The editor caches changes locally. You can click on the reset button on each page to restore it to the original state.

Closing here, since I don't believe there's anything to do.
