### ISSUE TITLE
tour: comment at line 26 is incorrect

### ISSUE THREAD

**Issue by danze** [golang/tour#750]
Context: https://tour.golang.org/methods/6

At line 26, replace this "ScaleFunc(p, 8) //56 42" with "ScaleFunc(p, 8) //96 72".

**Comment by ALTree** [comment]
Hi,

there's not `//56 42` comment in the code example on that page. My guess is that someone using the same browser added the comment. The editor caches changes locally. You can click on the reset button on each page to restore it to the original state.

Closing here, since I don't believe there's anything to do.
