### ISSUE TITLE
"go get golang.org/x/tour" does not install any binaries

### ISSUE THREAD

**Issue by gmcaguilar** [golang/tour#761]
As the title says, nothing happens when I execute `go get golang.org/x/tour` and the `$GOPATH/bin/` directory stays unchanged.

`tour` doesn't get installed, nor does `gotour` like it was mentioned in #637.

**Comment by rachari** [comment]
I checked this and as mentioned on the GitHub repo, a workspace is required for the mentioned binaries.

https://golang.org/doc/code.html#Workspaces

e.g. if the workspace is $HOME/go, then the binaries would be present under $HOME/go/bin once they are installed using the go get golang.org/x/tour command.

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

In case you're using BASH, then adding the above 2 lines to .bash_profile or .bashrc should make the tour command accessible from any location once the file has been sourced or if a new shell session is started.

**Comment by BryceDoganer** [comment]
I was having problems with this on mac and I found this [article](https://www.ardanlabs.com/blog/2016/05/installing-go-and-your-workspace.html) that helped. 

### Mac and Linux Users
Create folders named `code/go/src` in your `$HOME` folder:

`cd $HOME`
`mkdir -p ~/code/go/src`


**Update the `.bash_profile` file or your shell profile if there is another one you use:**

`cd $HOME`
`vim .bash_profile`

**At the top of the `.bash_profile` add these environmental variables:**

`export GOPATH="$HOME/code/go"`
`export PATH="$PATH:$GOPATH/bin"`

**Save the file and then source it:**

`source .bash_profile`

### Install & Run `tour`
`go get golang.org/x/tour`
`tour`

**Comment by murphyke** [comment]
Minor note: if you get `go: cannot find main module; see 'go help modules'` when you run `go get golang.org/x/tour`, it is probably because you have `GO111MODULE` set to `on` in your environment. In that case, just do: `GO111MODULE=off go get golang.org/x/tour`.

**Comment by Zedonboy** [comment]
Please go tour is not working. I cannot see any tour binary in my bin folder if GOPATH

**Comment by slimlime** [comment]
Could we please see expected directories + files output for this `go get golang.org/x/tour` command?

No `bin` files and attempting to run manual command workarounds into the local tour pkg src directory raises other errors such as ~No go files found

Not sure if it works for other people. Barrier to entry of onboarding new Go developers into the community

---

Digging up old deprecated versions of github `gotour` from the last decade do not appear to work either.

**Comment by slimlime** [comment]
It seems this issue #1203 has more substantial context and resolutions


Here is a fix for search engine listings that found this page first
`go install golang.org/x/website/tour@latest`

**Comment by alarmdesigns** [comment]
> It seems this issue #1203 has more substantial context and resolutions
> 
> Here is a fix for search engine listings that found this page first
> `go install golang.org/x/website/tour@latest`
> 
> #1218

This finally solved my problem.
Thank you very much. I wonder why the current documentation is outdated.
Now I can proceed learning.

**Comment by slimlime** [comment]
Thanks for the acknowledgement. Good to know this search result works and is helping people save time instead of spending hours of _new_ onboarding time wondering which exact parts are not behaving as intended.

https://github.com/golang/tour/issues/1218 - referred to comments, line changes and research.

From the context I gathered, there were parts being moved around and prepared in various golang repos - maybe a step was missed before a final "official" change that the documentation was waiting for
or it slipped through the cracks - seeing as many issues are untriaged/unresponded for years as well and the shift off GitHub to Google cs.opensource.google and golang.org (?)

**Comment by ALTree** [comment]
As noted, dup of #1203.

**Comment by lazy-boy4** [comment]
@alarmdesigns still couldn't find any binaries. It keep saying "package golang.org/x/website/tour@latest: cannot use path@version syntax in GOPATH mode"

I literally have no idea what to do.

**Comment by ALTree** [comment]
@lazy-boy4 which go version are you using?

**Comment by lazy-boy4** [comment]
@ALTree when I try to check it in terminal it says 1.15.15. But when I use VS Code it shows 1.17.
Maybe I have both installed.

**Comment by ALTree** [comment]
The instructions assume the user has a supported Go version; we support the last two version, so right now it's 1.16 or 1.17. Go 1.15 does not have module mode active by default, by the way, that's why it doesn't work. I suggest removing 1.15 and keeping 1.17. And be sure to run the suggested command from 1.17.

**Comment by lazy-boy4** [comment]
@ALTree hey that worked 😃 thank you sir!
