### ISSUE TITLE
tour: update the code for new go releases

### ISSUE THREAD

**Issue by Wdrwoman** [golang/tour#762]
Context: https://tour.golang.org/basics/6

Change the title above to describe your issue and add your feedback here, including code if necessary

package main

import (
	"fmt"
)

func swap(x, y string) (string, string) {
	return "", y + x
}

func main() {
	a, b := swap("hello", "world")
	fmt.Println(a, b)
}

**Comment by ALTree** [comment]
Thanks for the report.

That also works... but that lesson is about multiple return values so it's important for the code example to show a good example of that. Your `swap` implementation unnecessary returns an empty string as the first value, and it could just be `return y + x`, but then it wouldn't be an example of multiple returns.

Closing here, since I believe the example is okay.
