### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by halimess** [golang/tour#763]
Context: https://go-tour-kr.appspot.com/#3

go get link is not available.
The link is "code.google.com/p/go-tour/gotour"
It should be changed to "golang.org/x/tour"

**Comment by ALTree** [comment]
Hi, and thanks for reporting this.

We don't control or deploy the tour translations, so you'll need to report this to the person that maintains the korean translation. I think the repo is at  https://github.com/atomaths/go-tour-kr, but I don't know if the person that controls it is active on github. 

Closing here, since we cannot fix this.
