### ISSUE TITLE
tour: getting and running the tour locally doesn't work

### ISSUE THREAD

**Issue by josh-endries** [golang/tour#792]
Context: https://tour.golang.org/welcome/3

Just after installing Go

![image](https://user-images.githubusercontent.com/1500571/59977026-33ea3500-959a-11e9-9864-a00786c4c223.png)

**Comment by ALTree** [comment]
Thanks for the report.

You have to put the bin folder in GOPATH in your PATH environment variable. 

The tour assumes you installed Go following the installation instructions, which suggest you do that (add $GOPATH/bin to $PATH). Also see https://github.com/golang/tour/issues/631#issuecomment-458454047.

Closing here, since this is not a tour issue.
