### ISSUE TITLE
tour: Missing documentation on "Named Return Values"

### ISSUE THREAD

**Issue by bradwilzon** [golang/tour#808]
Context: https://tour.golang.org/basics/7

The tour for "Named Return Values" doesn't mention a crucial, yet short, piece of information that is documented in the golang spec (https://golang.org/ref/spec#Return_statements).

> A "return" statement that specifies results sets the result parameters before any deferred functions are executed.

Considering this one sentence is pretty consequential, I recommend adding it to the information in the tour for named returns.

---

Stretch goal, perhaps add an additional example that displays what this means:

```
package main

import "fmt"

func split(sum int) (x, y int) {
	defer func(){
		fmt.Println(x, y) // prints 5, 6
	}()
	
	x = 2
	y = 3
	
	return 5, 6
}

func main() {
	split(17)
}
```

**Comment by bradwilzon** [comment]
Without testing this myself (and then looking for it in the spec), I was doing redundant things like this:

```golang
func boomer(num int) (err error) {
	defer func(){
		// defer logging, metrics, etc. until the end
		if err != nil {
			println("log")
		}
	}()
	
	if num == 0 {
		// redundantly set err first
		err = errors.New("boom")
		return err
	}
	
	return nil
}
```

**Comment by bradwilzon** [comment]
Also, for what it's worth, the spec statement on this is a little confusing on first read.

**Comment by ALTree** [comment]
Defer has not yet been introduced at that point, so mentioning it would be quite confusing. The tour (especially the first lessons) are meant to be read by beginners, and in general it tries really hard not to confuse readers with information that is not absolutely necessary. 

Closing here, since I believe it would be better not to mention this in that lesson.
