### ISSUE TITLE
tour: GolandIDE inspection about using defer in a loop

### ISSUE THREAD

**Issue by dkarlovi** [golang/tour#824]
Context: https://tour.golang.org/flowcontrol/13

![Screenshot from 2019-09-19 14-11-15](https://user-images.githubusercontent.com/209225/65242905-837fc480-dae7-11e9-866a-12fa583cd1bf.png)

Maybe a additional paragraph explaining the considerations here?

**Comment by ALTree** [comment]
That check is definitely overzealous, there is not resource leak in this specific case. I don't think we need to complicate the text to account for possible misuses of defer. After all we already link to a blog post that dives deep into defer & co.. 

Closing here, since I don't believe we need to add more to that tour page.
