### ISSUE TITLE
tour: this is not a random sequence: 1, 1, 1, 1, 1, 1, ...

### ISSUE THREAD

**Issue by ken-graham** [golang/tour#852]
Context: https://tour.golang.org/basics/1

See subject.

**Comment by ALTree** [comment]
See text on that page:

> Note: The environment in which these programs are executed is deterministic, so each time you run the example program rand.Intn will return the same number. 

as explained a few lessons earlier:

> This makes it easier to cache programs by giving them deterministic output.

**Comment by mmdock** [comment]
@ALTree  this text does not display in the offline version of the tour.  

It is still not a random sequence in the offline version, so that should be updated
<img width="842" alt="Screen Shot 2020-06-18 at 11 48 03 AM" src="https://user-images.githubusercontent.com/2423465/85060222-b7147b80-b159-11ea-92a0-659e28254d26.png">
