### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by edoardottt** [golang/tour#914]
ITALIAN TOUR.

1. Here: https://go-tour-ita.appspot.com/basics/11

I tipi int, uint, **_and_** uintptr sono grandi normalmente 32 bit su sistemi da 32-bit e 64 bit su sistemi da 64-bit. Quando hai bisogno di un valore intero dovresti usare int a meno che tu non abbia particolari necessità di usare tipi di interi di dimensioni diverse o unsigned. 

I think that AND it should be '**e**', that is the italian conjunction.

2. Here: https://go-tour-ita.appspot.com/basics/14

Ma **_quanto_** la parte destra contiene una costante numerica non tipizzata, la nuova variabile può essere un int, float64, o complex128 a seconda della precisione del contesto:

I think it's '**_quando_**' .
quanto == how much
quando == when

Ps: I'm italian-native.

**Comment by ALTree** [comment]
Ciao,

this issue tracker is only for the official English version of the tour. The tour translations are not directly provided by the Go Project members, they are written, uploaded, and maintained by members of the community. 

We don't have commit rights on them, so we cannot fix their issues. What you can do is report the translation issue on the italian tour repository, here: https://github.com/alebaffa/go-tour-ita-trans

I'm closing this issue, since it is unfortunately not actionable.
