### ISSUE TITLE
tour: [each number must have two square roots in complex numbers ]

### ISSUE THREAD

**Issue by andriipospielov** [golang/tour#936]
Context: https://tour.golang.org/flowcontrol/5

Hello! 
In the given exercise, you show only one complex square root of a number.
according to the Fundamental theorem of algebra, there always must be always two of them.

My proposal is to modify the return block minorly, like this:

`return fmt.Sprint(math.Sqrt(x)) + " " + fmt.Sprint(-math.Sqrt(x))`

**Comment by ALTree** [comment]
Hi, an thanks for the report.

It's done that way to mimic the behaviour of [cmplx.Sqrt](https://golang.org/pkg/math/cmplx/#Sqrt), which only returns the principal value. This is typical for functions that manipulate complex numbers in programming languages (csqrt, from C, does the same).

I don't think doing otherwise would buy us anything: people that does not know how complex numbers work will be confused by the double return, and the ones who know will understand that we are returning the principal value. Again, this is extremely common in programming languages implementations of complex sqrt.

Closing here, since I believe the example should stay as it is.
