### ISSUE TITLE
tour: add Itoa hint to Stringers exercise

### ISSUE THREAD

**Issue by ghost** [golang/tour#94]
Context: https://tour.golang.org/methods/18

Suggestion : It may be useful to add some kind of helper to tell about string manipulation for this exercise

Rgds

**Comment by Tegmen** [comment]
It would be useful, if there was a "solution" to the exercises. 

Some "Hints" might be necessary, if not every operator or function needed to solve the exercise has yet been covered by the tour. For examle for the exercise "Stringers", hints could be:
"Use _Itoa(string)_ from package _strconv_ to convert an integer to a string"
"Strings can be concatenated with the '+' operator or with _Join_ from packages _strings_"

**Comment by ALTree** [comment]
At least something like

```
hint: you can use Itoa to convert an integer to its string representation
```

could help novices.

**Comment by ALTree** [comment]
I've looked into this and suggesting to use `Itoa` is not a great idea because `Itoa` takes an `int` and the IP type is made of `bytes`, so using `Itoa` would require a cast. The exercise solution uses `Sprintf`, which is the best choice in this case; but I don't think that needs to be described because it's used in the previous slide.

So I'd close this as WAI.
